language: go
go:
- master
before_install:
- go get github.com/modocache/gover
- go get github.com/gorilla/mux
- go get github.com/gorilla/handlers
- pip install --user awscli
- export PATH=$PATH:$HOME/.local/bin
script:
- go test -v ./...
- "./codecov_testing.sh"
after_success:
- bash <(curl -s https://codecov.io/bash) -f coverage.txt -t 0972d333-b670-4020-8e3b-45a440dcb759
deploy:
  provider: script
  script: chmod +x amazon_ecs.sh && sh amazon_ecs.sh
  on:
    branch: master
services:
- docker
env:
  global:
  - secure: U0kyPZk3sr3KDlPbFp+QM90tSo9pzmk2JVLypAbUmLO4YtKh3W27tu2WuZvF+1CyQd4CLJ88N3isbGYvaFjQKMlMKKD+UcQznqr3abOir1FQrVThTts5SYstcDmpqfM+p15dVDQ05yAF/U0UwUw22sO7TOLO4xpJNwMg+9UtCltkGBOYNK4C6NaUtNZj+6aMNMVYp/sm7iPEmISsmZjwi8bMFa737seQIrua6Kk4HCbXmJ36NhScRoPwWsHPFutsSQPneM0aIh8eWDB9YHTy10KQOheGuJGJ0+9GgFG5ox5xrwWjl8+9mPdhR+q0Im4b3y1qEZZfhF5QiJvJLOXRXyfuzLNUuDDNv0DeQQ47qBedgrfHvTE4+s+uqzZsNQvIOKpZyJ2Nir3TcCxE0txlmy3R73SY0xId3DVB5sTyAzPsnKX8hnpMmVYTAPFXSL+zmEy9POsVav00UGdk2e7Db297UrveNmbaGCeqazRthPQBiiqvpZqA0NBvse1Fm6CTkrBwI9tfaasgFzUIwqJAk8HuS/Uu0OlnUxOd4TAQt6g3Ie3xj3IzcTVgCWgiPAB+CJpOXhmQOSg9ZWqfT84w+4f9GuOUcmML5+0ppGRamzGcptgPut5P52Q+aeH1r9hOQdlEDQXRgIrpUz9vImI+/zMhOvxu0TIt6z4XA8jCc1k=
  - secure: cTBpRZpuu+aiCVeD/9MlSkRmvLEVxPchIG5WOysyedPJWQqsqyljxfVuMhSJQ7v/RtXZLTFJU0ggdP/0GFRgH4YIT7TKw/RnTKa0OayksK/y/6f98aUkrUFBzxD/kb5+OAl2zR1Rnel9mB+9o7iKcjml+cxsSdl9g/tI7+V6hcdN04QqxSBpZVqfzigJizYgDyJ1Aopqsm/jhKirbZo+oKP3NkeOgfaNK6jFYP9DPhbFay8rGkfkisv4Jzr2s8CBQloZ+ovw9P6FQ1FnLtowtCFYUDhDL8V+lukXiagkw8trwEoZ4NhQePt4PrgWcPDCmvHV1lsK80m/RRsZk1E3F2lThE9Aj8TnSQkcAQgz+EAD/Olm+w8fDA29I1lGbgM6mVS/DVvEVFKY6D4ohZf8JEHurUjbJ2EiofQ2PGD4jC/eR1tcKscl+Zb/Bu0eRWt9w6Jc02iKdH7nyFUegdztZyDaOf1RL8ZIf+M1p6umVc7MNEqq4dNFfHu7zgqiq6QMr2Ms19cmZZcJJawgIcfnLuWHByZBnNo2u7W18bcnBtQ0z1/l/kCtX+k5Q1h3j5wFwwxFF7pKTBQiqE+HvMUxF5EmK5VFSb6fiFMFv/iRR/KG1eAkxGACIkqi3Ra4hsJf6Lq4bewios4c7s932j26GfjVhN3enitAJk79xAmBeyk=
