language: go

go:
  - 1.x
  - 1.6		
  - 1.7.x
  - master

before_install:
  - go get github.com/modocache/gover
  - go get github.com/gorilla/mux
  - go get github.com/gorilla/handlers
  
  
script:
  - go test -v ./...
  # Run tests for code coverage as well
  - ./codecov_testing.sh

after_success:
  # Send coverage to codecov
  - bash < (curl -s https://codecov.io/bash) -f coverage.txt -t 0972d333-b670-4020-8e3b-45a440dcb759
